set (USE_INTERNAL_POCO_LIBRARY)

if ( NOT Poco_Foundation_LIBRARY )
	if ( NOT EXISTS "${kvClient_SOURCE_DIR}/third_party/poco/Foundation/include/Poco/Version.h" )
		find_package ( Poco REQUIRED Foundation Net JSON Util )
		message ( STATUS "Using Poco: ${Poco_VERSION}, ${Poco_LIBRARIES}" )
	else ()
		set ( USE_INTERNAL_POCO_LIBRARY 1 )
	endif ()
else ()
	set ( PocoFoundation ${Poco_Foundation_LIBRARY} )
	message ( STATUS "Poco has been already set." )
endif ()
